### ISSUE TITLE
Windows 11 "quarantine malicious Office document" VST fails, but Windows Security does "find threat," and then cleanup fails

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/test#41]
Steps:

Windows 11, Chrome browser: copy command for Windows
Paste and execute in Powershell

In Powershell, results show that (1) "control test failed" and (2) "clean up failed"

Windows Security shows "Threats found"

(I'm not totally sure whether the threat is just Flagged, or Flagged AND Quarantined. The malicious file -- tmpFBC6.exe -- is not in the Temp directory that the script says where it was written, which leads me to suspect it was quarantined?)

![vst](https://user-images.githubusercontent.com/118935081/214123879-25249cd5-2a6c-489c-b724-2ad5bc1555f1.png)

**Comment by nsreidy2** [comment]
Update: when I run it again (a third time; the screenshot above is from the 2nd run; both 1st and 2nd runs had similar results), the test passes.

So, there seems to be different behavior when running it several times.

**Comment by nsreidy2** [comment]
Adding screenshots from powershell, from the three runs.

![three_results_in_powershell](https://user-images.githubusercontent.com/118935081/214129191-256e4998-c105-410c-b225-498a7760cf3c.png)

**Comment by privateducky** [comment]
This is one of our findings we should have solved for (in tomorrow's release): test gets flagged OR excel file gets flagged (3rd case is probe gets flagged, but that's out of scope).

Let's retest this together tomorrow.

**Comment by privateducky** [comment]
@nsreidy2 let me know if you see any problems with the updated installation and demo scripts.

**Comment by nsreidy2** [comment]
thx @privateducky -- script and test look to be working well.

the "cleanup fails" situation (which I *think* isn't desired/intended behavior, it seems to me all rows should be "green" when things work right) is still present so I filed it as https://github.com/preludeorg/test/issues/48

**Comment by privateducky** [comment]
great! the cleanup failure is ok -- as that's also part of the overall test itself in this case (i.e., it can also identify a quarantine event). but our messaging has to be clearer on that... we're planning on adjusting some demo text this week and that note is in the proposed updates, so I'll close this ticket (initial problem solved) and ping you when the text updates are live.
