### ISSUE TITLE
windows demo - "access to path ... is denied" for windows probe

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/test#44]
Windows 10 Home, running powershell

When I opened powershell (possibly first time on this computer), the CLI put me in "C:\Windows\System32\WindowsPowerShell\v1.0\"

(Various resources on the internet say the the default path will be %HOMEDRIVE%%HOMEPATH%, so I don't know if me landing in that directory is just some weird coincidence or not; it seems to be the directory where Powershell itself lives.)

When, from this initial directory, I tried to run the pasted command, it errored out with an "access to the path ... is denied".

See screenshot. The top and bottom parts are 2 errors and the middle part is when it runs OK. I ran it -- got errors -- changed directory to one under \Users\ -- ran it again and it worked -- changed back to the original Powershell directory, ran it a third time, and got errors again.

It's possible this is just a very unlucky fluke. However, there's at least one directory location (and perhaps others) where the script errors out. Being more prescriptive about where to save the demo.ps1 file might make it a more hardened/resilient test. (Right now, it saves to .\demo.ps1. Perhaps better to save to %HOMEDRIVE%%HOMEPATH%\demo.ps1 or some other similar "known safe" location?

![wont_run_in_powershell_directory](https://user-images.githubusercontent.com/118935081/214220327-073e1dda-04eb-4973-ae28-8b5874cbf85d.png)

**Comment by nsreidy2** [comment]
On Windows 10 Home -- even when I change the directory in powershell (to a safe one), when I close and reopen Powershell, I was dropped back to the problematic location (C:\Windows\System32\WindowsPowerShell\v1.0). So it appears to be - on this machine for whatever reason - the default location it will open to (and therefore the demo script will fail). Perhaps it's a Win10Home thing, perhaps there's some other setting that's goofed up, perhaps something's not updated completely -- but whatever the reason, it creates a case where the demo will fail because the demo script file can't be written to that location.

**Comment by mireaulf** [comment]
It looks like your current user doesn't have access to write to that specific directory, which could be expected since it's a system directory.

- How did you start powershell?
- Can you run `(Get-Acl).Access.IdentityReference` in `C:\Windows\System32\WindowsPowerShell\v1.0` and send me the results directly
- Can you run `$env:username` and send me the result

**Comment by nsreidy2** [comment]
I started powershell by opening up the Start menu, typing "powershell" in
the Search box, and then selecting the result that says "powershell" (see
screenshot). There is another result called "Windows Powershell" that has
the same logo, and clicking THAT result sets the directory more correctly
(to my folder within C:\Users)

[image: image.png]

Will send responses for #s 2 and 3 directly

**Comment by privateducky** [comment]
@mireaulf two things to solve for on this today:
1. doing our best to direct the shell to a writable path by default (optional)
2. ensure nocturnal and raindrop both send a 126 code to us if a host cannot write to disk  (host incompatible)

**Comment by mireaulf** [comment]
@kenrick We need to update the command line for Windows to

`Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted; Invoke-WebRequest -UseBasicParsing -Uri **API_URL** -Headers @{'token'=**TOKEN**;'dos'='windows-x86_64'} -OutFile "${$env:TMP}\demo.ps1"; "$env:TMP\demo.ps1 **TOKEN**" | Invoke-Expression`
