### ISSUE TITLE
malicious file cleanup "fails" (windows malicious file VST)

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/test#48]
The cleanup "fails" -- I'm guessing because it can't delete the file it's supposed to delete, because the file was successfully quarantined.

Perhaps we're defining successful cleanup as "successful REMOVAL of file" -- and perhaps instead we should define successful cleanup (for this specific test) as "the file is no longer present." Otherwise we're trying to remove a file that is already supposed to have been removed by Windows Defender, if it's working properly.

![image](https://user-images.githubusercontent.com/118935081/214465751-7e664e69-684e-4027-b54c-37392310ba3d.png)

**Comment by privateducky** [comment]
Yep; this is a valid part of the quarantine process (the file isn't considered quarantined until after the handle is let go and reopened). we are planning on addressing that messaging in the demo script, so I'll keep this ticket alive until that is out, in case anyone else finds this answer vaguely helpful ;)

**Comment by privateducky** [comment]
@makk94 the demo script should never fail cleanup. 
if we hit this block:
```
    } catch [System.InvalidOperationException] {
        Write-Host -ForegroundColor Red $_
        Write-Host -ForegroundColor Red "`r`n[!] Clean up failed"
```
we should say "file already removed..."

**Comment by makk94** [comment]
Sometimes the test execution doesn't get quarantined but the cleanup execution does...

We shouldn't run cleanup if the test is quarantined - I just didn't add all the quarantine exit codes to my if statement
```
Write-Host "-----------------------------------------------------------------------------------------------------------
[3] Running cleanup
"
Start-Sleep -Seconds 3
if ($TestResult -eq 127) {
    Write-Host -ForegroundColor Green "`r`n[$($symbols.CHECKMARK)] Clean up is complete"
} else {
    ExecuteCleanup
}

```

@privateducky suppose I should add all "BLOCK" exit codes to that list, not just the two quarantine ones, right?

**Comment by privateducky** [comment]
yep, all block cases

**Comment by privateducky** [comment]
@nsreidy2 all reports I've heard are that this is now g2g. can you confirm and close if true?
