### ISSUE TITLE
Test is reporting a 0 status code on Linux, sometimes

### ISSUE THREAD

**Issue by privateducky** [preludeorg/test#52]
The malicious doc test has had reports of 0 status codes (the other in this screenshot) on two occasions. 

Can we figure out how this is possible?

![Screenshot 2023-01-31 at 10 42 20 AM](https://user-images.githubusercontent.com/49954156/215807301-5d001b52-457a-45f2-9a5f-1e61c8de3fea.png)

**Comment by bfuzzy1** [comment]
I'll take a look.

**Comment by privateducky** [comment]
We're now seeing an increase in OTHER/MISSING states.

![Screenshot 2023-02-07 at 1 22 03 PM](https://user-images.githubusercontent.com/49954156/217332499-94ac1a3c-3d75-403e-8f36-b5b05b184a12.png)

**Comment by bfuzzy1** [comment]
Linux-arm is me with a bad very very broken host. Pulled last 7 days of results and we're testing good across OS's except for that one. This test is being tested by the team this week hoping we can recreate the condition to find out why that is happening exactly.

**Comment by privateducky** [comment]
we believe this is caused by internal testing
